name: Publish Pages

on:
  workflow_dispatch:


jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Pages
        uses: actions/configure-pages@v5
        id: setup

      - name: Build Pages
        run: |
          yarn install
          yarn build
          cp dist/index.html dist/404.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy Pages
        uses: actions/deploy-pages@v4
